site_name: ScarLang
repo_url: https://github.com/20Koen02/ScarLang
repo_name: 20Koen02/ScarLang

theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
  palette:
    primary: pink
    accent: pink
  icon:
    repo: fontawesome/brands/git-alt

markdown_extensions:
  - admonition
  - pymdownx.smartsymbols
  - toc:
      permalink: true
